
create table MEDIUM_TBL (DTYPE varchar(31) not null, id bigint generated by default as identity, catId varchar(255), title varchar(255), publisher varchar(255), author varchar(255), genre varchar(255), isbn varchar(255), availability varchar(32), primary key (id));
create table USER_TBL (id bigint generated by default as identity, name varchar(256), surname varchar(256), userState varchar(32), primary key (id));
