drop table Medium if exists;
drop table User if exists;
create table Medium (DTYPE varchar(31) not null, id bigint generated by default as identity, catId varchar(255), title varchar(255), publisher varchar(255), author varchar(255), genre varchar(255), isbn varchar(255), availability varchar(32), primary key (id));
create table User (id bigint generated by default as identity, name varchar(256), surname varchar(256), userState varchar(32), primary key (id));
